services:
    olx-server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '4000:5000'
        env_file:
            - .env
        restart: unless-stopped
